version: '3'

volumes:
  pg_data:
  statik-taski:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - statik-taski:/backend_static
    depends_on:
      - db
  frontend:
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - statik-taski:/frontend_static
    build: ./frontend/

  gateway:
    build: ./gateway/
    volumes:
      - statik-taski:/staticfiles/
    ports:
      - 8000:80
